version: '3'
networks:
  app-network:
    driver: bridge

services:

  app:
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-store
    networks:
      - app-network
